print("Testing input function...")
name = input("Enter your name: ")
print(f"Hello, {name}!")
age = input("Enter your age: ")
print(f"You are {age} years old")
print(f"Type of age input: {type(age)}")
